
start ./main.exe N0
start ./main.exe N1
start ./main.exe N2
start ./main.exe N3
start ./main.exe N4
start ./main.exe N5
start ./main.exe N6
start ./main.exe N7
start ./main.exe N8
start ./main.exe N9
start ./main.exe N10
start ./main.exe N11
start ./main.exe N12
start ./main.exe N13
start ./main.exe N14
start ./main.exe N15
start ./main.exe N16
start ./main.exe N17
start ./main.exe N18
start ./main.exe N19
start ./main.exe N20
start ./main.exe N21
start ./main.exe N22
start ./main.exe N23
start ./main.exe N24
start ./main.exe N25
start ./main.exe N26
start ./main.exe N27
start ./main.exe N28
start ./main.exe N29
start ./main.exe N30
start ./main.exe N31
start ./main.exe N32
start ./main.exe N33
start ./main.exe N34
start ./main.exe N35
start ./main.exe N36
start ./main.exe N37
start ./main.exe N38
start ./main.exe N39
start ./main.exe N40
start ./main.exe N41
start ./main.exe N42
start ./main.exe N43
start ./main.exe N44
start ./main.exe N45
start ./main.exe N46
start ./main.exe N47
start ./main.exe N48
start ./main.exe N49
start ./main.exe N50
start ./main.exe N51
start ./main.exe N52
start ./main.exe N53
start ./main.exe N54
start ./main.exe N55
start ./main.exe N56
start ./main.exe N57
start ./main.exe N58
start ./main.exe N59
start ./main.exe N60
start ./main.exe N61
start ./main.exe N62
start ./main.exe N63
start ./main.exe N64
start ./main.exe N65
start ./main.exe N66
start ./main.exe N67
start ./main.exe N68
start ./main.exe N69
start ./main.exe N70
start ./main.exe N71
start ./main.exe N72
start ./main.exe N73
start ./main.exe N74
start ./main.exe N75
start ./main.exe N76
start ./main.exe N77
start ./main.exe N78
start ./main.exe N79
pause
start ./main.exe client
pause
